apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myloginapp-deployment
spec:
  selector:
    matchLabels:
      app: myloginapp
  # replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myloginapp
    spec:
      containers:
        - name: myloginapp
          image: myloginapp:mycicd
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
        