apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myloginapp-deployment
  namespace: default
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: myloginapp
  template:
    metadata:
      labels:
        app: myloginapp
    spec:
      containers:
        - name: myloginapp
          image: myloginapp:mycicd
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
            readinessProbe:
            httpGet:
              path: "/LoginWebApp"
        